
# syntax=docker/dockerfile:1
FROM python:ubuntu

RUN sudo apt update

RUN sudo apt install apache2
RUN sudo ufw allow ‘Apache’

RUN apt-get install python-pip
RUN sudo apt-get install libapache2-mod-wsgi-py3 python-dev-is-python3

WORKDIR /var/www
COPY . .

RUN pip3 install -r requirements.txt
RUN pip install -r requirements.txt

COPY ./validation-API.conf /etc/apache2/sites-available/

RUN  sudo a2ensite webApp 
RUN ststemctl reload apache2

COPY ./validation-API.wsgi .

EXPOSE 5000

RUN sudo service apache2 restart
